version: '3'
services:
  hungrifyapp:
    container_name: hungrifyapp
    build: ./Hungrify
    restart: always
    command: "npm start"
    ports:
      - "9000:8080"
    networks:
      - app-got
networks:
    app-got:
      driver: bridge
